2015-09-16 11:03:23,680 INFOL: fuck  [in/home/morph/lab/web/controllers/account.py:9]
2015-09-16 11:03:32,144 INFOL: fuck  [in/home/morph/lab/web/controllers/account.py:9]
2015-09-17 21:22:00,004 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-17 21:24:06,552 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 09:43:53,613 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 09:52:00,539 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:15:45,431 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:16:47,323 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:16:47,369 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:17:50,994 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:11,170 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:11,864 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:12,315 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:40,732 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:41,650 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:51,059 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:18:52,963 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:20:03,215 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:23:31,142 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:35:26,593 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:56:57,479 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:59:06,687 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 10:59:06,694 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:01:11,291 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:01:11,297 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:11:37,468 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:11:37,475 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:11:41,503 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:11:41,510 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:11:43,210 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 11:11:43,217 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:07:20,334 INFOL: send upload statusindexing files, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:07:20,709 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:07:22,890 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:23,898 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:24,787 INFOL: send upload statusuploading, 3% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:07:24,869 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:25,899 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:26,892 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:27,901 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:28,892 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:29,893 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:30,879 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:31,889 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:32,881 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,058 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:07:41,065 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:07:41,176 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,179 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,182 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,184 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,187 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,190 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,215 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,219 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:41,896 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:42,890 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:43,873 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:44,898 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:45,893 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:46,872 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:47,897 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:48,901 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:49,891 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:50,898 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:51,877 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:52,873 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:53,878 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:54,891 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:55,889 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:56,891 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:57,881 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:07:58,896 INFOL: send upload status:该邮箱没有注册 [in /home/morph/lab/web/controllers/api.py:73]
2015-09-21 14:08:15,781 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:08:15,782 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-21 14:08:21,752 INFOL: send upload status38 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:08:30,759 INFOL: send upload statusuploading, 66% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:08:30,763 INFOL: send upload status:uploading, 66%66%10619 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-21 14:09:06,705 INFOL: send upload status39 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:09:06,707 INFOL: send upload status:2015-09-21 14:09:06-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-21 14:11:49,971 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:11:49,983 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-21 14:12:41,099 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:12:41,099 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-21 14:12:42,300 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:12:42,307 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:12:42,314 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:12:51,418 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-21 14:12:51,418 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 08:55:47,512 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 08:57:21,215 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 08:57:21,215 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 08:57:24,119 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 08:57:24,119 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 08:57:35,998 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 08:57:35,998 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 08:57:37,554 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 08:57:37,561 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 08:57:37,568 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:03:48,698 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:03:48,712 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:03:48,719 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:04:55,788 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:04:55,788 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:04:57,003 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:04:57,010 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:04:57,017 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:14:47,268 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:14:47,268 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:15:46,028 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:15:46,029 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:15:47,063 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:15:47,069 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:15:47,076 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:16:48,682 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:16:48,689 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:16:48,695 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:16:50,439 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:16:50,439 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:16:52,071 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:16:52,071 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:00,394 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:00,394 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:01,738 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:01,738 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:02,581 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:02,581 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:03,919 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:03,920 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:04,621 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:04,621 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:11,889 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:11,889 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:12,519 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:12,519 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:13,079 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:13,079 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:13,481 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:13,481 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:13,981 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:13,981 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:14,758 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:14,758 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:15,887 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:15,888 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:16,619 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:16,619 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:17,549 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:17,549 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:18,321 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:18,321 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:18,991 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:18,991 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:30,408 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:30,408 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:31,117 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:31,117 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:32,350 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:32,350 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:33,021 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:33,021 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:33,599 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:33,599 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:34,900 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:34,900 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:35,519 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:35,519 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:36,300 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:36,301 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:37,229 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:37,229 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:38,489 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:38,489 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:39,077 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:39,078 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:40,230 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:40,230 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:41,410 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:41,410 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:42,459 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:42,459 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:43,330 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:43,330 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:44,013 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:44,014 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:44,890 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:44,890 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:45,632 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:45,632 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:46,269 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:46,269 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:46,577 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:46,577 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:46,990 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:46,990 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:47,739 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:47,739 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:59,029 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:59,029 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:17:59,630 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:17:59,631 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:18:00,080 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:18:00,080 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:19:23,200 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:19:23,201 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:19:42,999 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:19:42,999 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:19:43,768 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:19:43,768 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:19:44,371 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:19:44,371 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:19:44,769 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:19:44,769 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:148]
2015-09-22 09:27:39,917 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 13, in <module>
    os.environ['MOPRHFILE_CONF_DIR'] = MOPRHFILE_CONF_DIR
NameError: name 'MOPRHFILE_CONF_DIR' is not defined
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:27:39,918 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:28:47,396 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 17, in <module>
    from morphserv import morphfile_api
ImportError: No module named morphserv
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:28:47,396 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:28:57,167 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 17, in <module>
    from morphserv import morphfile_api
ImportError: No module named morphserv
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:28:57,168 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:28:58,481 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 17, in <module>
    from morphserv import morphfile_api
ImportError: No module named morphserv
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:28:58,481 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:28:59,870 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 17, in <module>
    from morphserv import morphfile_api
ImportError: No module named morphserv
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:28:59,870 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:32:19,021 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 17, in <module>
    from morphserv import morphfile_api
  File "/home/morph/morphfile-server_3.0.3/morphfile/lib64/python2.6/site-packages/morphserv/__init__.py", line 2, in <module>
    import service
  File "/home/morph/morphfile-server_3.0.3/morphfile/lib64/python2.6/site-packages/morphserv/service.py", line 100, in <module>
    raise ImportError("Morphserv cannot be imported, because environment variable %s is undefined." % ENVIRONMENT_VARIABLES[1])
ImportError: Morphserv cannot be imported, because environment variable MORPHFILE_CONF_DIR is undefined.
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:32:19,021 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:32:20,250 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/morph/lab/web/utils/server_info.py", line 17, in <module>
    from morphserv import morphfile_api
  File "/home/morph/morphfile-server_3.0.3/morphfile/lib64/python2.6/site-packages/morphserv/__init__.py", line 2, in <module>
    import service
  File "/home/morph/morphfile-server_3.0.3/morphfile/lib64/python2.6/site-packages/morphserv/service.py", line 100, in <module>
    raise ImportError("Morphserv cannot be imported, because environment variable %s is undefined." % ENVIRONMENT_VARIABLES[1])
ImportError: Morphserv cannot be imported, because environment variable MORPHFILE_CONF_DIR is undefined.
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-22 09:32:20,250 INFOL: su:None st:None [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:34:53,890 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:35:34,690 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:35:41,214 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:35:42,639 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:35:45,332 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:35:47,053 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:35:48,121 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:36:52,139 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:37:01,091 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-22 09:37:01,981 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 18:53:58,863 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 18:55:51,724 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 18:55:55,697 INFOL: su:2237872861.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 20:25:58,170 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 20:26:17,979 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 20:26:33,068 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 20:28:00,959 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 20:36:18,204 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 20:38:11,104 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 21:30:49,077 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:149]
2015-09-24 21:50:35,643 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:152]
2015-09-24 22:02:04,847 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:02:04,856 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:02:04,862 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:02:22,314 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:02:22,321 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:02:22,327 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:04:50,112 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:04:50,119 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:04:50,126 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-24 22:42:20,609 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:42:20,616 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:42:23,053 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:42:24,759 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:42:58,795 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:43:01,059 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:43:01,062 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-24 22:43:06,956 INFOL: send upload statusuploading, 91% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:43:06,962 INFOL: send upload status:uploading, 91%91%10566 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-24 22:43:08,185 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:43:08,191 INFOL: send upload status:2015-09-24 22:43:08-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-24 22:43:38,614 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:43:39,889 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:43:40,588 INFOL: send upload status3 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:47:20,409 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:47:20,422 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:48:24,829 INFOL: send upload status5 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:48:27,175 INFOL: send upload status5 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:52:20,425 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:52:20,436 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:53:01,059 INFOL: send upload status10 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:57:20,421 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 22:57:20,429 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 23:00:13,470 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:166]
2015-09-24 23:02:20,419 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 23:02:20,429 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 23:07:20,396 INFOL: send upload status24 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-24 23:07:20,413 INFOL: send upload status24 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:04:07,105 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:04:36,882 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:166]
2015-09-25 16:04:40,434 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:166]
2015-09-25 16:04:43,602 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:166]
2015-09-25 16:04:45,340 INFOL: su:2290354435.0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:166]
2015-09-25 16:04:48,051 INFOL: su:0 st:2147483648.0 [in /home/morph/lab/web/controllers/status.py:166]
2015-09-25 16:31:03,794 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:31:03,801 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:31:04,286 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:31:04,292 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:36:01,601 INFOL: send upload status17 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:36:04,340 INFOL: send upload status17 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:36:05,528 INFOL: send upload status17 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:40:26,063 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:41:01,511 INFOL: send upload status17 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:41:01,518 INFOL: send upload status17 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:42:01,774 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-25 16:46:01,529 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:46:01,535 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:51:01,500 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:51:01,506 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:56:01,559 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 16:56:01,565 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:01:01,491 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:01:01,498 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:06:01,565 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:06:01,580 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:11:01,550 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:11:01,559 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:16:01,578 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-25 17:16:01,584 INFOL: send upload status18 hours ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:18:04,004 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 13:24:42,523 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 13:31:57,858 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 13:51:46,374 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 13:52:00,275 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:00,287 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:02,080 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:21,889 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:21,891 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 13:52:22,888 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:22,897 INFOL: send upload status:2015-09-26 13:52:22-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 13:52:27,479 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:29,246 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:29,253 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:29,256 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 13:52:29,934 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:29,943 INFOL: send upload status:2015-09-26 13:52:29-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 13:52:33,589 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:33,625 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:35,301 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:40,888 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:43,188 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:43,793 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:45,899 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:46,350 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:52:46,648 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:53:04,834 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:53:07,863 INFOL: send upload status1 day ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:54:35,228 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:54:35,234 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:59:35,218 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 13:59:35,225 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:06,811 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:07,960 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:09,887 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:09,891 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:02:10,539 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:10,541 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:02:11,887 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:11,891 INFOL: send upload status:2015-09-26 14:02:11-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:02:13,416 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:02:15,880 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:04:28,559 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:04:36,476 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:04:36,481 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:04:36,984 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:04:36,989 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:04:38,748 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:04:38,755 INFOL: send upload status:uploading, 0%0%9318 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:05:37,926 INFOL: send upload status3 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:05:37,930 INFOL: send upload status:2015-09-26 14:05:37-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:05:44,924 INFOL: send upload statusuploading, 57% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:05:44,930 INFOL: send upload status:uploading, 57%57%11098 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:06:33,888 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:06:33,891 INFOL: send upload status:2015-09-26 14:06:33-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-26 14:06:42,710 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:06:43,146 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:06:44,201 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:09:35,177 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:09:35,191 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:09:47,584 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:09:47,591 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:12:39,108 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:12:39,115 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:12:39,122 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:12:39,128 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:12:39,136 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:14:35,263 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:14:35,271 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:19:35,204 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:19:35,212 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:24:35,264 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:24:35,272 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:27:04,871 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:29:35,228 INFOL: send upload status24 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:29:35,235 INFOL: send upload status24 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:34:35,199 INFOL: send upload status29 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:34:35,206 INFOL: send upload status29 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:38:45,322 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:38:45,329 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:38:45,336 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:38:45,344 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:38:45,351 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:39:35,199 INFOL: send upload status34 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:39:35,206 INFOL: send upload status34 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:44:35,198 INFOL: send upload status39 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:44:35,206 INFOL: send upload status39 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:48:21,852 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:48:21,859 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:48:21,865 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:48:21,874 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:48:21,881 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-26 14:49:35,223 INFOL: send upload status44 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:49:35,231 INFOL: send upload status44 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:54:35,216 INFOL: send upload status49 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:54:35,224 INFOL: send upload status49 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:59:35,176 INFOL: send upload status54 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 14:59:35,184 INFOL: send upload status54 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 15:04:35,216 INFOL: send upload status59 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 15:04:35,224 INFOL: send upload status59 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 15:09:35,207 INFOL: send upload status1 hour ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 15:09:35,221 INFOL: send upload status1 hour ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 15:14:35,209 INFOL: send upload status1 hour ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-26 15:14:35,215 INFOL: send upload status1 hour ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:29:32,304 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:29:32,314 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:29:33,300 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:29:35,938 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:29:35,941 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:29:36,895 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:29:36,902 INFOL: send upload status:2015-09-30 14:29:36-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:30:53,729 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:30:55,914 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:30:55,917 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:30:56,909 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:30:56,912 INFOL: send upload status:2015-09-30 14:30:56-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:30:59,159 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:06,645 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:06,730 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:07,740 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:08,150 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:20,637 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2015-09-30 14:31:33,456 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:34,708 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:35,591 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:35,728 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:42,469 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:49,768 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:49,995 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:31:50,430 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:32:19,600 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:32:19,606 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:33:36,438 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:33:36,958 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:33:56,130 INFOL: send upload status4 days ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:00,895 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:00,901 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:34:01,095 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:01,100 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:34:07,339 INFOL: send upload statusuploading, 7% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:07,342 INFOL: send upload status:uploading, 7%7%8604 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:34:13,069 INFOL: send upload statusuploading, 14% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:13,080 INFOL: send upload status:uploading, 14%14%10681 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:34:32,307 INFOL: send upload statusuploading, 37% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:32,312 INFOL: send upload status:uploading, 37%37%10636 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:34:32,363 INFOL: send upload statusuploading, 37% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:32,377 INFOL: send upload status:uploading, 37%37%10636 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:34:43,748 INFOL: send upload statusuploading, 51% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:34:43,754 INFOL: send upload status:uploading, 51%51%10074 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:35:02,931 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:02,934 INFOL: send upload status:2015-09-30 14:35:02-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:35:10,563 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:12,935 INFOL: send upload statusuploading, 92% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:12,940 INFOL: send upload status:uploading, 92%92%10569 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:35:13,458 INFOL: send upload statusuploading, 93% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:13,461 INFOL: send upload status:uploading, 93%93%10569 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:35:19,897 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:19,900 INFOL: send upload status:2015-09-30 14:35:19-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:35:21,560 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:25,869 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:35:26,329 INFOL: send upload status4 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:36:24,915 INFOL: send upload status5 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:36:25,929 INFOL: send upload status5 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:10,200 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:14,808 INFOL: send upload statusindexing files, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:14,811 INFOL: send upload status:indexing files, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:37:14,889 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:14,892 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:37:15,891 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:15,894 INFOL: send upload status:2015-09-30 14:37:15-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:37:22,931 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:23,465 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:25,202 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:25,224 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:26,378 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:31,958 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:44,897 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:37:46,158 INFOL: send upload status6 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:38:43,575 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:38:44,048 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:38:50,697 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:38:51,569 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:38:54,883 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:38:55,135 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:10,639 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:10,900 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:11,266 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:14,189 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:15,738 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:16,106 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:17,858 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:19,086 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:32,157 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:32,164 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:40,918 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:39:42,271 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:40:01,058 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:40:02,239 INFOL: send upload status2 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:40:19,509 INFOL: send upload status3 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:40:20,617 INFOL: send upload status3 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:32,209 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:32,268 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:32,316 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:34,565 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:34,573 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:35,391 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:37,692 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:37,697 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:42,660 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:42,666 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:44,699 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:44,705 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:47,898 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:47,904 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:51,489 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:51,495 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:54,035 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:54,043 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:57,118 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:44:57,124 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:00,447 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:00,454 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:03,395 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:03,401 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:35,125 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:35,130 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:36,350 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:36,356 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:44,366 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:44,373 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:46,799 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:46,805 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:49,898 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:49,904 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:51,398 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:51,404 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:52,875 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:52,883 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:53,619 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:53,626 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:58,086 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:58,094 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:58,599 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:45:58,605 INFOL: send upload status8 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:46:30,025 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:46:30,041 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:46:30,047 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:46:30,053 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:46:52,693 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:46:52,699 INFOL: send upload status9 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:11,897 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:11,900 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:11,904 INFOL: send upload statusuploading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:11,907 INFOL: send upload status:uploading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:24,999 INFOL: send upload statusuploading, 3% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:25,003 INFOL: send upload status:uploading, 3%3%10753 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:25,008 INFOL: send upload statusuploading, 3% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:25,012 INFOL: send upload status:uploading, 3%3%10753 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:25,694 INFOL: send upload statusuploading, 4% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:25,699 INFOL: send upload status:uploading, 4%4%10701 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:25,703 INFOL: send upload statusuploading, 4% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:25,707 INFOL: send upload status:uploading, 4%4%10701 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:33,508 INFOL: send upload statusuploading, 7% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:33,512 INFOL: send upload status:uploading, 7%7%10657 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:33,516 INFOL: send upload statusuploading, 7% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:33,519 INFOL: send upload status:uploading, 7%7%10657 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:33,529 INFOL: send upload statusuploading, 7% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:33,533 INFOL: send upload status:uploading, 7%7%10657 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:33,547 INFOL: send upload statusuploading, 7% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:33,553 INFOL: send upload status:uploading, 7%7%10657 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:42,840 INFOL: send upload statusuploading, 11% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:42,851 INFOL: send upload status:uploading, 11%11%10789 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:42,856 INFOL: send upload statusuploading, 11% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:42,862 INFOL: send upload status:uploading, 11%11%10789 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:43,205 INFOL: send upload statusuploading, 11% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:43,210 INFOL: send upload status:uploading, 11%11%10789 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:43,214 INFOL: send upload statusuploading, 11% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:43,218 INFOL: send upload status:uploading, 11%11%10789 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:57,620 INFOL: send upload statusuploading, 18% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:57,624 INFOL: send upload status:uploading, 18%18%10357 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:57,628 INFOL: send upload statusuploading, 18% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:57,631 INFOL: send upload status:uploading, 18%18%10357 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:58,540 INFOL: send upload statusuploading, 18% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:58,543 INFOL: send upload status:uploading, 18%18%10613 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:47:58,548 INFOL: send upload statusuploading, 18% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:47:58,552 INFOL: send upload status:uploading, 18%18%10613 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:48:13,948 INFOL: send upload status11 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:48:13,953 INFOL: send upload status:2015-09-30 14:48:13-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:48:13,958 INFOL: send upload status11 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:48:21,946 INFOL: send upload statusuploading, 26% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:48:21,950 INFOL: send upload status:uploading, 26%26%10816 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:48:21,956 INFOL: send upload statusuploading, 26% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:48:21,959 INFOL: send upload status:uploading, 26%26%10816 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:21,937 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:21,942 INFOL: send upload status:2015-09-30 14:49:21-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:21,948 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:31,936 INFOL: send upload statusuploading, 52% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:31,940 INFOL: send upload status:uploading, 52%52%10745 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:31,944 INFOL: send upload statusuploading, 52% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:31,947 INFOL: send upload status:uploading, 52%52%10745 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:32,345 INFOL: send upload statusuploading, 53% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:32,351 INFOL: send upload status:uploading, 53%53%10745 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:32,399 INFOL: send upload statusuploading, 53% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:32,403 INFOL: send upload status:uploading, 53%53%10745 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:34,909 INFOL: send upload statusuploading, 53% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:34,913 INFOL: send upload status:uploading, 53%53%10902 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:38,468 INFOL: send upload statusuploading, 55% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:38,472 INFOL: send upload status:uploading, 55%55%10975 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:40,069 INFOL: send upload statusuploading, 55% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:40,073 INFOL: send upload status:uploading, 55%55%10794 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:41,156 INFOL: send upload statusuploading, 55% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:41,159 INFOL: send upload status:uploading, 55%55%10925 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:42,152 INFOL: send upload statusuploading, 56% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:42,156 INFOL: send upload status:uploading, 56%56%10187 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:43,372 INFOL: send upload statusuploading, 56% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:43,380 INFOL: send upload status:uploading, 56%56%10739 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:51,520 INFOL: send upload statusuploading, 60% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:51,524 INFOL: send upload status:uploading, 60%60%10920 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:58,126 INFOL: send upload statusuploading, 62% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:58,130 INFOL: send upload status:uploading, 62%62%10660 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:49:58,719 INFOL: send upload statusuploading, 62% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:49:58,722 INFOL: send upload status:uploading, 62%62%10503 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:50:20,571 INFOL: send upload statusuploading, 70% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:50:20,575 INFOL: send upload status:uploading, 70%70%10916 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:50:22,169 INFOL: send upload statusuploading, 70% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:50:22,173 INFOL: send upload status:uploading, 70%70%10353 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:50:31,929 INFOL: send upload status13 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:50:31,932 INFOL: send upload status:2015-09-30 14:50:31-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:50:41,948 INFOL: send upload statusuploading, 78% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:50:41,951 INFOL: send upload status:uploading, 78%78%10643 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:50:54,469 INFOL: send upload statusuploading, 82% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:50:54,473 INFOL: send upload status:uploading, 82%82%10765 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:50:54,996 INFOL: send upload statusuploading, 83% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:50:55,001 INFOL: send upload status:uploading, 83%83%10471 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:51:05,968 INFOL: send upload statusuploading, 87% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:05,979 INFOL: send upload status:uploading, 87%87%10977 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:51:07,067 INFOL: send upload statusuploading, 88% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:07,070 INFOL: send upload status:uploading, 88%88%10350 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:51:08,879 INFOL: send upload statusuploading, 89% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:08,883 INFOL: send upload status:uploading, 89%89%10932 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:51:08,928 INFOL: send upload statusuploading, 89% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:08,931 INFOL: send upload status:uploading, 89%89%10932 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:51:32,889 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:32,892 INFOL: send upload status:2015-09-30 14:51:32-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 14:51:33,326 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:49,587 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:50,173 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:51,182 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:51:51,670 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:52:02,810 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:52:04,030 INFOL: send upload status14 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:52:57,420 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:52:58,239 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:53:00,008 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:53:00,026 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:53:13,555 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:53:13,949 INFOL: send upload status16 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:53:21,620 INFOL: send upload status16 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:53:21,949 INFOL: send upload status16 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:54:32,125 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:54:32,141 INFOL: send upload status7 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:59:32,135 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:59:32,151 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:59:48,607 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 14:59:50,285 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:00:09,701 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:00:10,589 INFOL: send upload status12 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:00:11,709 INFOL: send upload status13 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:00:16,336 INFOL: send upload status13 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:00:17,941 INFOL: send upload status13 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:00:18,418 INFOL: send upload status13 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:02:27,071 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:02:27,082 INFOL: send upload status15 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:04:32,119 INFOL: send upload status17 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:04:32,129 INFOL: send upload status17 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:05:51,466 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:05:52,282 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:05:53,400 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:05:53,697 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:03,049 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:03,640 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:07,384 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:07,718 INFOL: send upload status18 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:29,747 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:30,200 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:38,050 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:38,339 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:06:53,890 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:07:01,894 INFOL: send upload status19 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:07,429 INFOL: send upload status20 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:09,297 INFOL: send upload status20 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:11,719 INFOL: send upload status21 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:12,229 INFOL: send upload status21 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:36,729 INFOL: send upload status21 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:37,338 INFOL: send upload status21 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:47,926 INFOL: send upload status21 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:08:48,808 INFOL: send upload status21 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:27,303 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:27,999 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:30,620 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:30,641 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:32,153 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:32,192 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:48,073 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:48,743 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:49,475 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:09:49,568 INFOL: send upload status22 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:02,854 INFOL: send upload statusdownloading, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:02,860 INFOL: send upload status:downloading, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 15:13:08,343 INFOL: send upload statusdownloading, 24% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:08,351 INFOL: send upload status:downloading, 24%24%10654 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 15:13:11,289 INFOL: send upload statusdownloading, 44% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:11,292 INFOL: send upload status:downloading, 44%44%10601 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 15:13:12,568 INFOL: send upload statusdownloading, 50% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:12,574 INFOL: send upload status:downloading, 50%50%10660 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 15:13:21,997 INFOL: send upload status26 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:22,007 INFOL: send upload status:2015-09-30 15:13:22-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 15:13:43,136 INFOL: send upload statusindexing files, 0% [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:43,140 INFOL: send upload status:indexing files, 0%0%0 [in /home/morph/lab/web/controllers/api.py:61]
2015-09-30 15:13:43,940 INFOL: send upload status26 minutes ago [in /home/morph/lab/web/controllers/api.py:25]
2015-09-30 15:13:43,943 INFOL: send upload status:2015-09-30 15:13:43-1%-1 [in /home/morph/lab/web/controllers/api.py:61]
2015-10-10 19:37:44,576 ERRORL: Traceback (most recent call last):
  File "/home/morph/lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/morph/lab/web/utils/read_user_ip.py", line 18, in get_user_repo
    engine = create_engine(morphfile_db)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
 [in /home/morph/lab/web/utils/get_server_info.py:65]
2016-06-13 09:38:50,166 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 45, in _get_user_id
    return get_user_ip(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 8, in get_user_ip
    morphweb_db = load_config().MORPHWEB_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHWEB_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-13 09:38:50,167 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 17, in get_user_repo
    morphfile_db = load_config().MOPRHFILE_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MOPRHFILE_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-13 09:38:50,848 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().MORPHCNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHCNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-13 09:39:20,131 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 45, in _get_user_id
    return get_user_ip(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 8, in get_user_ip
    morphweb_db = load_config().MORPHWEB_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHWEB_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-13 09:39:20,131 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 17, in get_user_repo
    morphfile_db = load_config().MOPRHFILE_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MOPRHFILE_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-13 09:39:23,649 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().MORPHCNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHCNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-13 09:42:07,832 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().MORPHCNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHCNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:28:33,188 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 45, in _get_user_id
    return get_user_ip(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 8, in get_user_ip
    morphweb_db = load_config().MORPHWEB_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHWEB_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:28:33,188 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 17, in get_user_repo
    morphfile_db = load_config().MOPRHFILE_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MOPRHFILE_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:37:58,882 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().MORPHCNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHCNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:38:11,412 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 45, in _get_user_id
    return get_user_ip(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 8, in get_user_ip
    morphweb_db = load_config().MORPHWEB_DB
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHWEB_DB'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:38:11,423 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 53, in _get_repo_id
    return get_user_repo(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/read_user_ip.py", line 21, in get_user_repo
    ret = session.execute("select repo_id from RepoOwner where owner_id = :email limit 1", {'email': email})
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1034, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:38:18,070 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().MORPHCNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHCNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:41:59,015 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().DEFAULT_CNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'DEFAULT_CNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:42:10,117 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().DEFAULT_CNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'DEFAULT_CNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:42:46,267 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 10, in <module>
    MORPHSERVER_PY_PACKAGE = load_config().MORPHSERVER_PY_PACKAGE
AttributeError: type object 'ProductionConfig' has no attribute 'MORPHSERVER_PY_PACKAGE'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:43:42,816 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 18, in <module>
    from seaserv import api as morphfile_api
  File "/usr/local/lib/python2.7/dist-packages/seaserv/__init__.py", line 2, in <module>
    import service
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 31, in <module>
    CCNET_CONF_PATH = _load_path_from_env('CCNET_CONF_DIR')
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 25, in _load_path_from_env
    raise ImportError("Seaserv cannot be imported, because environment variable %s is undefined." % key)
ImportError: Seaserv cannot be imported, because environment variable CCNET_CONF_DIR is undefined.
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:44:22,212 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 18, in <module>
    from seaserv import api as morphfile_api
  File "/usr/local/lib/python2.7/dist-packages/seaserv/__init__.py", line 2, in <module>
    import service
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 63, in <module>
    SERVER_ID = config.get('General', 'ID')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'General'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:48:07,224 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 18, in <module>
    from seaserv import api as morphfile_api
  File "/usr/local/lib/python2.7/dist-packages/seaserv/__init__.py", line 2, in <module>
    import service
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 63, in <module>
    SERVER_ID = config.get('General', 'ID')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'General'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 14:49:00,891 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 19, in <module>
    from seaserv import api as morphfile_api
  File "/usr/local/lib/python2.7/dist-packages/seaserv/__init__.py", line 2, in <module>
    import service
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 63, in <module>
    SERVER_ID = config.get('General', 'ID')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'General'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:00:08,996 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 7, in <module>
    MORPHCNET_CONF_DIR = load_config().DEFAULT_CCNET_CONF_DIR
AttributeError: type object 'ProductionConfig' has no attribute 'DEFAULT_CCNET_CONF_DIR'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:00:54,204 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 19, in <module>
    from seaserv import api as morphfile_api
  File "/usr/local/lib/python2.7/dist-packages/seaserv/__init__.py", line 2, in <module>
    import service
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 63, in <module>
    SERVER_ID = config.get('General', 'ID')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'General'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:07:27,302 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 19, in <module>
    from seaserv import api as morphfile_api
  File "/usr/local/lib/python2.7/dist-packages/seaserv/__init__.py", line 2, in <module>
    import service
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 66, in <module>
    SERVER_ID = config.get('General', 'ID')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'General'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:09:15,873 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 37, in _get_quota
    return server_api.get_quota_usage(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 22, in get_quota_usage
    used = morphfile_api.get_user_self_usage(username) + morphfile_api.get_user_share_usage(username)
AttributeError: 'module' object has no attribute 'get_user_self_usage'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:12:54,053 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 37, in _get_quota
    return server_api.get_quota_usage(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 22, in get_quota_usage
    used = morphfile_api.get_user_self_usage(username) + morphfile_api.get_user_share_usage(username)
AttributeError: 'module' object has no attribute 'get_user_self_usage'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:17:27,615 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 37, in _get_quota
    return server_api.get_quota_usage(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 22, in get_quota_usage
    morphfile_api = api.SeafileApi()
AttributeError: 'module' object has no attribute 'SeafileApi'
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:18:54,226 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 36, in _get_quota
    import server_info as server_api
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 19, in <module>
    from seaserv import SeafileApi as morphfile_api
ImportError: cannot import name SeafileApi
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:20:03,495 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 37, in _get_quota
    return server_api.get_quota_usage(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 23, in get_quota_usage
    used = morphfile_api.get_user_self_usage(username) + morphfile_api.get_user_share_usage(username)
  File "/usr/local/lib/python2.7/dist-packages/seaserv/api.py", line 511, in get_user_self_usage
    return seafserv_threaded_rpc.get_user_quota_usage(username)
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 71, in call_remote_func_sync
    client = self.pool.get_client()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/pool.py", line 29, in get_client
    client = self._create_client()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/pool.py", line 21, in _create_client
    client.connect_daemon()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/client.py", line 128, in connect_daemon
    return self.connect_daemon_with_pipe()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/client.py", line 110, in connect_daemon_with_pipe
    raise NetworkError("Can't connect to daemon")
NetworkError: Can't connect to daemon
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:21:08,718 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 37, in _get_quota
    return server_api.get_quota_usage(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 23, in get_quota_usage
    used = morphfile_api.get_user_self_usage(username) + morphfile_api.get_user_share_usage(username)
  File "/usr/local/lib/python2.7/dist-packages/seaserv/api.py", line 511, in get_user_self_usage
    return seafserv_threaded_rpc.get_user_quota_usage(username)
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 71, in call_remote_func_sync
    client = self.pool.get_client()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/pool.py", line 29, in get_client
    client = self._create_client()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/pool.py", line 21, in _create_client
    client.connect_daemon()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/client.py", line 128, in connect_daemon
    return self.connect_daemon_with_pipe()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/client.py", line 110, in connect_daemon_with_pipe
    raise NetworkError("Can't connect to daemon")
NetworkError: Can't connect to daemon
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
2016-06-15 15:27:10,010 ERRORL: Traceback (most recent call last):
  File "/home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py", line 37, in _get_quota
    return server_api.get_quota_usage(username)
  File "/home/axe/haiwen/src/morph_lab/web/utils/server_info.py", line 23, in get_quota_usage
    used = morphfile_api.get_user_self_usage(username) + morphfile_api.get_user_share_usage(username)
  File "/usr/local/lib/python2.7/dist-packages/seaserv/api.py", line 511, in get_user_self_usage
    return seafserv_threaded_rpc.get_user_quota_usage(username)
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 71, in call_remote_func_sync
    client = self.pool.get_client()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/pool.py", line 29, in get_client
    client = self._create_client()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/pool.py", line 21, in _create_client
    client.connect_daemon()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/client.py", line 128, in connect_daemon
    return self.connect_daemon_with_pipe()
  File "/home/axe/haiwen/seafile-server-5.1.2/seafile/lib64/python2.6/site-packages/ccnet/client.py", line 110, in connect_daemon_with_pipe
    raise NetworkError("Can't connect to daemon")
NetworkError: Can't connect to daemon
 [in /home/axe/haiwen/src/morph_lab/web/utils/get_server_info.py:65]
